schema_version = "1.0.0"

id = "import_daz"
version = "5.2.0"
name = "DAZ Importer"
tagline = "Importer for native DAZ files (.duf, .dsf)"
maintainer = "Thomas Larsson <thomas.larsson.01@gmail.com>"
type = "add-on"
website = "https://github.com/Diffeomorphic/import_daz"
tags = ["Import-Export", "Animation"]
blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-2.0-or-later",
]
copyright = [
  "2016-2026 Thomas Larsson",
]

[permissions]
files = "Import DAZ files from disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
   ".git*",
  "/.git/",
  "runtime/__pycache__/",
  "runtime/.git/"
]